//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { UsersEntity } from './db/Users.entity';
import { VendorsEntity } from './db/Vendors.entity';
import { CustomersEntity } from './db/Customers.entity';
import { InventoryEntity } from './db/Inventory.entity';
import { ProductsEntity } from './db/Products.entity';
import { ProductCategoriesEntity } from './db/ProductCategories.entity';
import { DiscountsEntity } from './db/Discounts.entity';
import { ShoppingCartEntity } from './db/ShoppingCart.entity';
import { OrdersEntity } from './db/Orders.entity';
import { OrderDetailsEntity } from './db/OrderDetails.entity';
import { PaymentsEntity } from './db/Payments.entity';
import { ReviewsEntity } from './db/Reviews.entity';
import { SupportTicketsEntity } from './db/SupportTickets.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      UsersEntity,
      VendorsEntity,
      CustomersEntity,
      InventoryEntity,
      ProductsEntity,
      ProductCategoriesEntity,
      DiscountsEntity,
      ShoppingCartEntity,
      OrdersEntity,
      OrderDetailsEntity,
      PaymentsEntity,
      ReviewsEntity,
      SupportTicketsEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Users: [
        {
          username: 'username 1',
          email: 'email 1',
          password: 'password 1',
          role: 'role 1',
          id: 98,
        },
        {
          username: 'username 2',
          email: 'email 2',
          password: 'password 2',
          role: 'role 2',
          id: 76,
        },
        {
          username: 'username 3',
          email: 'email 3',
          password: 'password 3',
          role: 'role 3',
          id: 8,
        },
        {
          username: 'username 4',
          email: 'email 4',
          password: 'password 4',
          role: 'role 4',
          id: 21,
        },
        {
          username: 'username 5',
          email: 'email 5',
          password: 'password 5',
          role: 'role 5',
          id: 80,
        },
      ],
      Vendors: [
        {
          companyName: 'companyName 1',
          contactName: 'contactName 1',
          email: 'email 1',
          password: 'password 1',
          id: 38,
        },
        {
          companyName: 'companyName 2',
          contactName: 'contactName 2',
          email: 'email 2',
          password: 'password 2',
          id: 23,
        },
        {
          companyName: 'companyName 3',
          contactName: 'contactName 3',
          email: 'email 3',
          password: 'password 3',
          id: 44,
        },
        {
          companyName: 'companyName 4',
          contactName: 'contactName 4',
          email: 'email 4',
          password: 'password 4',
          id: 75,
        },
        {
          companyName: 'companyName 5',
          contactName: 'contactName 5',
          email: 'email 5',
          password: 'password 5',
          id: 89,
        },
      ],
      Customers: [
        {
          customerName: 'customerName 1',
          email: 'email 1',
          password: 'password 1',
          billingAddress: 'billingAddress 1',
          shippingAddress: 'shippingAddress 1',
          country: 'country 1',
          phone: 'phone 1',
          id: 2,
        },
        {
          customerName: 'customerName 2',
          email: 'email 2',
          password: 'password 2',
          billingAddress: 'billingAddress 2',
          shippingAddress: 'shippingAddress 2',
          country: 'country 2',
          phone: 'phone 2',
          id: 92,
        },
        {
          customerName: 'customerName 3',
          email: 'email 3',
          password: 'password 3',
          billingAddress: 'billingAddress 3',
          shippingAddress: 'shippingAddress 3',
          country: 'country 3',
          phone: 'phone 3',
          id: 10,
        },
        {
          customerName: 'customerName 4',
          email: 'email 4',
          password: 'password 4',
          billingAddress: 'billingAddress 4',
          shippingAddress: 'shippingAddress 4',
          country: 'country 4',
          phone: 'phone 4',
          id: 84,
        },
        {
          customerName: 'customerName 5',
          email: 'email 5',
          password: 'password 5',
          billingAddress: 'billingAddress 5',
          shippingAddress: 'shippingAddress 5',
          country: 'country 5',
          phone: 'phone 5',
          id: 31,
        },
      ],
      Inventory: [
        { product: 1, quantity: 1, lowStockThreshold: 1, id: 2 },
        { product: 2, quantity: 2, lowStockThreshold: 2, id: 3 },
        { product: 3, quantity: 3, lowStockThreshold: 3, id: 6 },
        { product: 4, quantity: 4, lowStockThreshold: 4, id: 90 },
        { product: 5, quantity: 5, lowStockThreshold: 5, id: 24 },
      ],
      Products: [
        {
          productName: 'productName 1',
          vendor: 1,
          price: 0.01,
          weight: 0.68,
          description: 'description 1',
          thumbnail: 'thumbnail 1',
          image: 'image 1',
          category: 1,
          creationDate: '2024-08-04T01:33:18.641Z',
          stock: 1,
          id: 25,
        },
        {
          productName: 'productName 2',
          vendor: 2,
          price: 0.58,
          weight: 0.03,
          description: 'description 2',
          thumbnail: 'thumbnail 2',
          image: 'image 2',
          category: 2,
          creationDate: '2024-09-18T21:55:53.684Z',
          stock: 2,
          id: 23,
        },
        {
          productName: 'productName 3',
          vendor: 3,
          price: 0.62,
          weight: 0.17,
          description: 'description 3',
          thumbnail: 'thumbnail 3',
          image: 'image 3',
          category: 3,
          creationDate: '2024-01-28T03:03:53.543Z',
          stock: 3,
          id: 10,
        },
        {
          productName: 'productName 4',
          vendor: 4,
          price: 0.38,
          weight: 0.71,
          description: 'description 4',
          thumbnail: 'thumbnail 4',
          image: 'image 4',
          category: 4,
          creationDate: '2023-05-24T20:09:06.056Z',
          stock: 4,
          id: 82,
        },
        {
          productName: 'productName 5',
          vendor: 5,
          price: 0.69,
          weight: 0.24,
          description: 'description 5',
          thumbnail: 'thumbnail 5',
          image: 'image 5',
          category: 5,
          creationDate: '2024-05-13T20:28:42.252Z',
          stock: 5,
          id: 7,
        },
      ],
      ProductCategories: [
        { category: 'category 1', id: 91 },
        { category: 'category 2', id: 54 },
        { category: 'category 3', id: 81 },
        { category: 'category 4', id: 25 },
        { category: 'category 5', id: 81 },
      ],
      Discounts: [
        {
          product: 1,
          discountType: 'discountType 1',
          description: 'description 1',
          discountAmount: 0.61,
          discountPercent: 0.26,
          id: 76,
        },
        {
          product: 2,
          discountType: 'discountType 2',
          description: 'description 2',
          discountAmount: 0.48,
          discountPercent: 0.18,
          id: 27,
        },
        {
          product: 3,
          discountType: 'discountType 3',
          description: 'description 3',
          discountAmount: 0.72,
          discountPercent: 0.54,
          id: 31,
        },
        {
          product: 4,
          discountType: 'discountType 4',
          description: 'description 4',
          discountAmount: 0.97,
          discountPercent: 0.17,
          id: 63,
        },
        {
          product: 5,
          discountType: 'discountType 5',
          description: 'description 5',
          discountAmount: 0.92,
          discountPercent: 0.94,
          id: 100,
        },
      ],
      ShoppingCart: [
        { customer: 1, product: 1, priceAtPurchase: 0.84, quantity: 1, id: 71 },
        { customer: 2, product: 2, priceAtPurchase: 0.68, quantity: 2, id: 90 },
        { customer: 3, product: 3, priceAtPurchase: 0.91, quantity: 3, id: 95 },
        { customer: 4, product: 4, priceAtPurchase: 0.3, quantity: 4, id: 45 },
        { customer: 5, product: 5, priceAtPurchase: 0.75, quantity: 5, id: 84 },
      ],
      Orders: [
        {
          orderNumber: 'orderNumber 1',
          customer: 1,
          totalAmount: 0.15,
          vat: 0.54,
          totalAmountWithVat: 0.66,
          shippingCost: 0.6,
          shippingAddress: 'shippingAddress 1',
          orderAddress: 'orderAddress 1',
          orderEmail: 'orderEmail 1',
          orderDate: '2024-10-22T07:34:12.362Z',
          orderStatus: 'orderStatus 1',
          trackingNo: 'trackingNo 1',
          id: 3,
        },
        {
          orderNumber: 'orderNumber 2',
          customer: 2,
          totalAmount: 0.6,
          vat: 0.19,
          totalAmountWithVat: 0.64,
          shippingCost: 0.71,
          shippingAddress: 'shippingAddress 2',
          orderAddress: 'orderAddress 2',
          orderEmail: 'orderEmail 2',
          orderDate: '2024-12-21T17:48:09.002Z',
          orderStatus: 'orderStatus 2',
          trackingNo: 'trackingNo 2',
          id: 62,
        },
        {
          orderNumber: 'orderNumber 3',
          customer: 3,
          totalAmount: 0.99,
          vat: 0.33,
          totalAmountWithVat: 0.26,
          shippingCost: 0.37,
          shippingAddress: 'shippingAddress 3',
          orderAddress: 'orderAddress 3',
          orderEmail: 'orderEmail 3',
          orderDate: '2023-11-27T01:04:38.383Z',
          orderStatus: 'orderStatus 3',
          trackingNo: 'trackingNo 3',
          id: 83,
        },
        {
          orderNumber: 'orderNumber 4',
          customer: 4,
          totalAmount: 0.55,
          vat: 0.77,
          totalAmountWithVat: 0.48,
          shippingCost: 0.75,
          shippingAddress: 'shippingAddress 4',
          orderAddress: 'orderAddress 4',
          orderEmail: 'orderEmail 4',
          orderDate: '2024-04-11T09:44:30.820Z',
          orderStatus: 'orderStatus 4',
          trackingNo: 'trackingNo 4',
          id: 51,
        },
        {
          orderNumber: 'orderNumber 5',
          customer: 5,
          totalAmount: 0.69,
          vat: 0.28,
          totalAmountWithVat: 0.28,
          shippingCost: 0.86,
          shippingAddress: 'shippingAddress 5',
          orderAddress: 'orderAddress 5',
          orderEmail: 'orderEmail 5',
          orderDate: '2024-02-27T03:59:57.381Z',
          orderStatus: 'orderStatus 5',
          trackingNo: 'trackingNo 5',
          id: 98,
        },
      ],
      OrderDetails: [
        {
          orderNumber: 1,
          line: 1,
          product: 1,
          price: 0.37,
          quantity: 1,
          id: 87,
        },
        {
          orderNumber: 2,
          line: 2,
          product: 2,
          price: 0.43,
          quantity: 2,
          id: 72,
        },
        {
          orderNumber: 3,
          line: 3,
          product: 3,
          price: 0.03,
          quantity: 3,
          id: 0,
        },
        {
          orderNumber: 4,
          line: 4,
          product: 4,
          price: 0.04,
          quantity: 4,
          id: 40,
        },
        {
          orderNumber: 5,
          line: 5,
          product: 5,
          price: 0.88,
          quantity: 5,
          id: 27,
        },
      ],
      Payments: [
        {
          orderNumber: 1,
          amount: 0.71,
          paymentMethod: 'paymentMethod 1',
          paymentDate: '2024-12-05T05:57:16.446Z',
          paymentStatus: 'paymentStatus 1',
          id: 64,
        },
        {
          orderNumber: 2,
          amount: 0.21,
          paymentMethod: 'paymentMethod 2',
          paymentDate: '2025-01-12T13:34:31.961Z',
          paymentStatus: 'paymentStatus 2',
          id: 61,
        },
        {
          orderNumber: 3,
          amount: 0.81,
          paymentMethod: 'paymentMethod 3',
          paymentDate: '2024-06-08T14:47:52.922Z',
          paymentStatus: 'paymentStatus 3',
          id: 97,
        },
        {
          orderNumber: 4,
          amount: 0.44,
          paymentMethod: 'paymentMethod 4',
          paymentDate: '2025-01-18T03:18:11.236Z',
          paymentStatus: 'paymentStatus 4',
          id: 90,
        },
        {
          orderNumber: 5,
          amount: 0.24,
          paymentMethod: 'paymentMethod 5',
          paymentDate: '2024-12-25T14:26:56.806Z',
          paymentStatus: 'paymentStatus 5',
          id: 66,
        },
      ],
      Reviews: [
        {
          product: 1,
          customer: 1,
          vendor: 1,
          rating: 0.67,
          reviewDetails: 'reviewDetails 1',
          date: '2024-03-10T04:24:01.070Z',
          id: 15,
        },
        {
          product: 2,
          customer: 2,
          vendor: 2,
          rating: 0.15,
          reviewDetails: 'reviewDetails 2',
          date: '2024-01-24T09:50:50.059Z',
          id: 40,
        },
        {
          product: 3,
          customer: 3,
          vendor: 3,
          rating: 0.13,
          reviewDetails: 'reviewDetails 3',
          date: '2024-07-17T17:56:21.371Z',
          id: 24,
        },
        {
          product: 4,
          customer: 4,
          vendor: 4,
          rating: 0.5,
          reviewDetails: 'reviewDetails 4',
          date: '2023-12-05T05:05:07.065Z',
          id: 92,
        },
        {
          product: 5,
          customer: 5,
          vendor: 5,
          rating: 0.49,
          reviewDetails: 'reviewDetails 5',
          date: '2024-07-15T03:27:21.248Z',
          id: 18,
        },
      ],
      SupportTickets: [
        {
          user: 1,
          customer: 1,
          description: 'description 1',
          status: 'status 1',
          creationDate: '2023-08-21T14:57:53.665Z',
          resolutionDate: '2024-07-25T01:03:56.482Z',
          id: 22,
        },
        {
          user: 2,
          customer: 2,
          description: 'description 2',
          status: 'status 2',
          creationDate: '2025-03-08T22:40:43.975Z',
          resolutionDate: '2023-12-18T23:24:25.240Z',
          id: 39,
        },
        {
          user: 3,
          customer: 3,
          description: 'description 3',
          status: 'status 3',
          creationDate: '2023-06-27T09:42:18.886Z',
          resolutionDate: '2023-10-04T02:49:43.011Z',
          id: 4,
        },
        {
          user: 4,
          customer: 4,
          description: 'description 4',
          status: 'status 4',
          creationDate: '2024-02-06T11:01:02.479Z',
          resolutionDate: '2024-06-15T02:43:45.030Z',
          id: 18,
        },
        {
          user: 5,
          customer: 5,
          description: 'description 5',
          status: 'status 5',
          creationDate: '2023-11-14T17:00:50.579Z',
          resolutionDate: '2024-03-12T03:53:21.414Z',
          id: 20,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('UsersEntity', data.Users);
      await this.SeedResource('VendorsEntity', data.Vendors);
      await this.SeedResource('CustomersEntity', data.Customers);
      await this.SeedResource('InventoryEntity', data.Inventory);
      await this.SeedResource('ProductsEntity', data.Products);
      await this.SeedResource(
        'ProductCategoriesEntity',
        data.ProductCategories,
      );
      await this.SeedResource('DiscountsEntity', data.Discounts);
      await this.SeedResource('ShoppingCartEntity', data.ShoppingCart);
      await this.SeedResource('OrdersEntity', data.Orders);
      await this.SeedResource('OrderDetailsEntity', data.OrderDetails);
      await this.SeedResource('PaymentsEntity', data.Payments);
      await this.SeedResource('ReviewsEntity', data.Reviews);
      await this.SeedResource('SupportTicketsEntity', data.SupportTickets);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
